server:
  port: 8005
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/coinfiesta?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: CoinFiesta96*
    driver-class-name: com.mysql.cj.jdbc.Driver 
    
mybatis:
  mapper-locations:
  - /mappers/*.xml  
      
    
